#theme: jekyll-theme-cayman
theme: jekyll-swiss
gems:
  - jekyll-seo-tag

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: MTDTR_tk

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: black

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Le Site Web de Suika AKIYAMA
description: Suika AKIYAMA, composeur, étudiant, etc.
github_repo: sueakiyama.github.io # the GitHub repo name for your project
github_username: sueakiyama

url: "https://sueakiyama.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
