#theme: jekyll-theme-cayman
theme: jekyll-swiss
gems:
  - jekyll-seo-tag

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: MTDTR_tk
